name: arm-template-cd-release-$(rev:r)

trigger:
  # none
  branches:
    include:
      - 'main'
      - 'master'
      - 'release*'
  paths:
    include:
      - infra/*
      - code/*

resources:
  pipelines:
  - pipeline: ciartifacts
    source: iac-data-landing-ci-cd-dev  # ci用のPipeline名に修正する

# pr: # PRトリガーはAzure Reposの場合、branch policyで実装します。https://docs.microsoft.com/ja-jp/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#pr-triggers
  # branches:
  #   include:
  #     - 'main'
  #     - 'release/*'
  # paths:
  #   include:
  #     - infra/*
  #     - code/*
  #     - .ado/workflows/azure-pipelines-ci-qa-bicep.yml
variables:
  - name: AZURE_RESOURCE_MANAGER_CONNECTION_NAME
    value: "azure-devops-service-connection" # Update to '{yourResourceManagerConnectionName}'
  - name: AZURE_LOCATION
    value: "japaneast" # Update to '{yourLocationName}'
  - name: AZURE_SUBSCRIPTION_ID
    value: "" # Update to '{yourAZURE_SUBSCRIPTION_ID}'
  - name: RESOURCE_GROUP_NAME
    value: "" # Update to '{yourRESOURCE_GROUP_NAME}'

stages:
  - stage: Deploy_prod
    displayName: "Deploy ARM templates to dev"
    # condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    jobs:
    - template: templates/jobs/arm-template-deploy-job.yml
      parameters:
        ENVIRONMENT_NAME: 'prod'
        TARGET_AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
        TARGET_RESOURCE_GROUP_NAME: $(RESOURCE_GROUP_NAME)
        TARGET_AZURE_LOCATION: $(AZURE_LOCATION)
        PARAMETER_FILEPATH: ciartifacts/infra/params_prod.json
        DEPLOY_FILEPATH: ciartifacts/infra/main.json
        
