name: build-bicep

trigger:
  none

pr:
  branches:
    include:
      - 'main'
      - 'release/*'
  paths:
    include:
      - infra/*
      - code/*
      - .ado/workflows/azure-pipelines.yml

variables:
  - name: AZURE_RESOURCE_MANAGER_CONNECTION_NAME
    value: "azure-devops-service-connection" # Update to '{yourResourceManagerConnectionName}'
  - name: AZURE_LOCATION
    value: "japaneast" # Update to '{yourResourceManagerConnectionName}'
  - name: AZURE_SUBSCRIPTION_ID
    value: "" # Update to '{yourResourceManagerConnectionName}'
  - name: RESOURCE_GROUP_NAME
    value: "" # Update to '{yourResourceManagerConnectionName}'


stages:
  - stage: Validation
    displayName: "Validation of IaC templates"
    jobs:
      - job: Validation
        displayName: "Validation of IaC templates"
        continueOnError: false
        pool:
          vmImage: "ubuntu-latest"

        steps:
          # Checkout code
          - checkout: self
            name: checkout_repository
            displayName: Checkout repository
            submodules: true
            lfs: false
            clean: true
            continueOnError: false
            enabled: true

          # building bicep into ARM
          - task: AzureCLI@2  
            displayName: 'Build bicep artifact' 
            inputs: 
              azureSubscription: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
              scriptType: 'pscore'  
              scriptLocation: 'inlineScript'  
              inlineScript: |
                $file = "$(System.DefaultWorkingDirectory)/infra/deployRG.bicep"            
                New-Item -ItemType Directory -Force -Path $(build.artifactstagingdirectory)/infra
                az bicep build --file $file --outdir $(build.artifactstagingdirectory)/infra

          # Deploy ARM - validation
          - task: AzureResourceManagerTemplateDeployment@3
            name: ARM_validation
            displayName: ARM - validation
            enabled: true
            continueOnError: false
            inputs:
              deploymentScope: "ResouceGroup"
              ConnectedServiceName: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
              subscriptionId: $(AZURE_SUBSCRIPTION_ID) 
              resourceGroupName: $(RESOURCE_GROUP_NAME)
              location: $(AZURE_LOCATION)
              templateLocation: "Linked artifact"
              csmFile: "$(build.artifactstagingdirectory)/infra/deploy.json"
              csmParametersFile: "$(System.DefaultWorkingDirectory)/infra/params_dev.json"
              deploymentMode: "Validation"

          # Deploy ARM - what-if
          - task: AzureCLI@2
            name: ARM_whatif
            displayName: Deploy ARM - what-if
            enabled: true
            continueOnError: false
            inputs:
              azureSubscription: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az account set `
                  --subscription $(AZURE_SUBSCRIPTION_ID)
                
                az deployment sub what-if `
                  --location $(AZURE_LOCATION) `
                  --subscription $(AZURE_SUBSCRIPTION_ID) `
                  --exclude-change-types Ignore NoChange Unsupported `
                  --template-file "$(build.artifactstagingdirectory)/infra/deploy.json"`
                  --parameters "$(System.DefaultWorkingDirectory)/infra/params_dev.json" `
                  --result-format "FullResourcePayloads"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(build.artifactstagingdirectory)'
              artifact: 'iac'
              publishLocation: 'pipeline'